/*
 * Copyright 2015-2018 Marcel Piestansky
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */
package feathers.themes {

    import starling.textures.Texture;
    import starling.textures.TextureAtlas;

    /**
     * Icons for the Uniflat theme. These icons are initialized by
     * <code>UniflatMobileThemeWithIcons</code> and <code>UniflatMobileThemeWithAssetManagerAndIcons</code>.
     */
    public class UniflatMobileThemeIcons {

        public static var _3DRotationTexture:Texture;
        public static var accessibilityTexture:Texture;
        public static var accountBalanceTexture:Texture;
        public static var accountBalanceWalletTexture:Texture;
        public static var accountBoxTexture:Texture;
        public static var accountChildTexture:Texture;
        public static var accountCircleTexture:Texture;
        public static var addBoxTexture:Texture;
        public static var addCircleTexture:Texture;
        public static var addCircleOutlineTexture:Texture;
        public static var addTexture:Texture;
        public static var addShoppingCartTexture:Texture;
        public static var alarmAddTexture:Texture;
        public static var alarmTexture:Texture;
        public static var alarmOffTexture:Texture;
        public static var alarmOnTexture:Texture;
        public static var androidTexture:Texture;
        public static var announcementTexture:Texture;
        public static var appsTexture:Texture;
        public static var archiveTexture:Texture;
        public static var arrowBackTexture:Texture;
        public static var arrowDropDownCircleTexture:Texture;
        public static var arrowDropDownTexture:Texture;
        public static var arrowDropUpTexture:Texture;
        public static var arrowForwardTexture:Texture;
        public static var aspectRatioTexture:Texture;
        public static var assessmentTexture:Texture;
        public static var assignmentTexture:Texture;
        public static var assignmentIndTexture:Texture;
        public static var assignmentLateTexture:Texture;
        public static var assignmentReturnTexture:Texture;
        public static var assignmentReturnedTexture:Texture;
        public static var assignmentTurnedInTexture:Texture;
        public static var autoRenewTexture:Texture;
        public static var backspaceTexture:Texture;
        public static var backupTexture:Texture;
        public static var blockTexture:Texture;
        public static var bookTexture:Texture;
        public static var bookmarkTexture:Texture;
        public static var bookmarkOutlineTexture:Texture;
        public static var bugReportTexture:Texture;
        public static var cachedTexture:Texture;
        public static var cakeTexture:Texture;
        public static var cancelTexture:Texture;
        public static var checkCircleTexture:Texture;
        public static var checkTexture:Texture;
        public static var chevronLeftTexture:Texture;
        public static var chevronRightTexture:Texture;
        public static var classTexture:Texture;
        public static var clearTexture:Texture;
        public static var closeTexture:Texture;
        public static var contentCopyTexture:Texture;
        public static var contentCutTexture:Texture;
        public static var contentPasteTexture:Texture;
        public static var createTexture:Texture;
        public static var creditCardTexture:Texture;
        public static var dashboardTexture:Texture;
        public static var deleteTexture:Texture;
        public static var descriptionTexture:Texture;
        public static var dnsTexture:Texture;
        public static var domainTexture:Texture;
        public static var doneAllTexture:Texture;
        public static var doneTexture:Texture;
        public static var draftsTexture:Texture;
        public static var errorTexture:Texture;
        public static var eventTexture:Texture;
        public static var exitToAppTexture:Texture;
        public static var expandLessTexture:Texture;
        public static var expandMoreTexture:Texture;
        public static var exploreTexture:Texture;
        public static var extensionTexture:Texture;
        public static var faceTexture:Texture;
        public static var favoriteTexture:Texture;
        public static var favoriteOutlineTexture:Texture;
        public static var filterListTexture:Texture;
        public static var findInPageTexture:Texture;
        public static var findReplaceTexture:Texture;
        public static var flagTexture:Texture;
        public static var flipToBackTexture:Texture;
        public static var flipToFrontTexture:Texture;
        public static var forwardTexture:Texture;
        public static var fullscreenExitTexture:Texture;
        public static var fullscreenTexture:Texture;
        public static var gestureTexture:Texture;
        public static var getAppTexture:Texture;
        public static var gradeTexture:Texture;
        public static var groupAddTexture:Texture;
        public static var groupTexture:Texture;
        public static var groupWorkTexture:Texture;
        public static var helpTexture:Texture;
        public static var highlightRemoveTexture:Texture;
        public static var historyTexture:Texture;
        public static var homeTexture:Texture;
        public static var httpsTexture:Texture;
        public static var inboxTexture:Texture;
        public static var infoTexture:Texture;
        public static var infoOutlineTexture:Texture;
        public static var inputTexture:Texture;
        public static var invertColorsTexture:Texture;
        public static var labelTexture:Texture;
        public static var labelOutlineTexture:Texture;
        public static var languageTexture:Texture;
        public static var launchTexture:Texture;
        public static var linkTexture:Texture;
        public static var listTexture:Texture;
        public static var locationCityTexture:Texture;
        public static var lockTexture:Texture;
        public static var lockOpenTexture:Texture;
        public static var lockOutlineTexture:Texture;
        public static var loyaltyTexture:Texture;
        public static var mailTexture:Texture;
        public static var markUnreadMailboxTexture:Texture;
        public static var markUnreadTexture:Texture;
        public static var menuTexture:Texture;
        public static var moodTexture:Texture;
        public static var moreHorizontalTexture:Texture;
        public static var moreVerticalTexture:Texture;
        public static var noteAddTexture:Texture;
        public static var notificationsTexture:Texture;
        public static var notificationsNoneTexture:Texture;
        public static var notificationsOffTexture:Texture;
        public static var notificationsOnTexture:Texture;
        public static var notificationsPausedTexture:Texture;
        public static var openInBrowserTexture:Texture;
        public static var openInNewTexture:Texture;
        public static var openWithTexture:Texture;
        public static var pageViewTexture:Texture;
        public static var pagesTexture:Texture;
        public static var partyModeTexture:Texture;
        public static var paymentTexture:Texture;
        public static var peopleTexture:Texture;
        public static var peopleOutlineTexture:Texture;
        public static var permCameraMicTexture:Texture;
        public static var permContactCalTexture:Texture;
        public static var permDataSettingTexture:Texture;
        public static var permDeviceInfoTexture:Texture;
        public static var permIdentityTexture:Texture;
        public static var permMediaTexture:Texture;
        public static var permPhoneMsgTexture:Texture;
        public static var permScanWifiTexture:Texture;
        public static var personAddTexture:Texture;
        public static var personTexture:Texture;
        public static var personOutlineTexture:Texture;
        public static var pictureInPictureTexture:Texture;
        public static var plusOneTexture:Texture;
        public static var pollTexture:Texture;
        public static var polymerTexture:Texture;
        public static var printTexture:Texture;
        public static var publicTexture:Texture;
        public static var queryBuilderTexture:Texture;
        public static var questionAnswerTexture:Texture;
        public static var receiptTexture:Texture;
        public static var redeemTexture:Texture;
        public static var redoTexture:Texture;
        public static var refreshTexture:Texture;
        public static var removeCircleTexture:Texture;
        public static var removeCircleOutlineTexture:Texture;
        public static var removeTexture:Texture;
        public static var reorderTexture:Texture;
        public static var replyAllTexture:Texture;
        public static var replyTexture:Texture;
        public static var reportTexture:Texture;
        public static var reportProblemTexture:Texture;
        public static var restoreTexture:Texture;
        public static var roomTexture:Texture;
        public static var saveTexture:Texture;
        public static var scheduleTexture:Texture;
        public static var schoolTexture:Texture;
        public static var searchTexture:Texture;
        public static var selectAllTexture:Texture;
        public static var sendTexture:Texture;
        public static var settingsApplicationsTexture:Texture;
        public static var settingsBackupRestoreTexture:Texture;
        public static var settingsBluetoothTexture:Texture;
        public static var settingsCellTexture:Texture;
        public static var settingsDisplayTexture:Texture;
        public static var settingsEthernetTexture:Texture;
        public static var settingsTexture:Texture;
        public static var settingsInputAntennaTexture:Texture;
        public static var settingsInputComponentTexture:Texture;
        public static var settingsInputCompositeTexture:Texture;
        public static var settingsInputHDMITexture:Texture;
        public static var settingsInputSVideoTexture:Texture;
        public static var settingsOverscanTexture:Texture;
        public static var settingsPhoneTexture:Texture;
        public static var settingsPowerTexture:Texture;
        public static var settingsRemoteTexture:Texture;
        public static var settingsVoiceTexture:Texture;
        public static var shareTexture:Texture;
        public static var shopTexture:Texture;
        public static var shopTwoTexture:Texture;
        public static var shoppingBasketTexture:Texture;
        public static var shoppingCartTexture:Texture;
        public static var sortTexture:Texture;
        public static var speakerNotesTexture:Texture;
        public static var spellCheckTexture:Texture;
        public static var starRateTexture:Texture;
        public static var starsTexture:Texture;
        public static var storeTexture:Texture;
        public static var subjectTexture:Texture;
        public static var supervisorAccountTexture:Texture;
        public static var swapHorizontalTexture:Texture;
        public static var swapVerticalCircleTexture:Texture;
        public static var swapVerticalTexture:Texture;
        public static var systemUpdateTvTexture:Texture;
        public static var tabTexture:Texture;
        public static var tabUnselectedTexture:Texture;
        public static var textFormatTexture:Texture;
        public static var theatersTexture:Texture;
        public static var thumbDownTexture:Texture;
        public static var thumbUpTexture:Texture;
        public static var thumbsUpDownTexture:Texture;
        public static var tocTexture:Texture;
        public static var todayTexture:Texture;
        public static var trackChangesTexture:Texture;
        public static var translateTexture:Texture;
        public static var trendingDownTexture:Texture;
        public static var trendingNeutralTexture:Texture;
        public static var trendingUpTexture:Texture;
        public static var turnedInTexture:Texture;
        public static var turnedInNotTexture:Texture;
        public static var undoTexture:Texture;
        public static var unfoldLessTexture:Texture;
        public static var unfoldMoreTexture:Texture;
        public static var verifiedUserTexture:Texture;
        public static var videocamTexture:Texture;
        public static var viewAgendaTexture:Texture;
        public static var viewArrayTexture:Texture;
        public static var viewCarouselTexture:Texture;
        public static var viewColumnTexture:Texture;
        public static var viewDayTexture:Texture;
        public static var viewHeadlineTexture:Texture;
        public static var viewListTexture:Texture;
        public static var viewModuleTexture:Texture;
        public static var viewQuiltTexture:Texture;
        public static var viewStreamTexture:Texture;
        public static var viewWeekTexture:Texture;
        public static var visibilityTexture:Texture;
        public static var visibilityOffTexture:Texture;
        public static var walletGiftCardTexture:Texture;
        public static var walletMembershipTexture:Texture;
        public static var walletTravelTexture:Texture;
        public static var warningTexture:Texture;
        public static var whatsHotTexture:Texture;
        public static var workTexture:Texture;

        internal static function initialize( atlas:TextureAtlas ):void {
            _3DRotationTexture = getTextureForIcon( atlas, "3d-rotation-icon" );
            accessibilityTexture = getTextureForIcon( atlas, "accessibility-icon" );
            accountBalanceTexture = getTextureForIcon( atlas, "account-balance-icon" );
            accountBalanceWalletTexture = getTextureForIcon( atlas, "account-balance-wallet-icon" );
            accountBoxTexture = getTextureForIcon( atlas, "account-box-icon" );
            accountChildTexture = getTextureForIcon( atlas, "account-child-icon" );
            accountCircleTexture = getTextureForIcon( atlas, "account-circle-icon" );
            addBoxTexture = getTextureForIcon( atlas, "add-box-icon" );
            addCircleTexture = getTextureForIcon( atlas, "add-circle-icon" );
            addCircleOutlineTexture = getTextureForIcon( atlas, "add-circle-outline-icon" );
            addTexture = getTextureForIcon( atlas, "add-icon" );
            addShoppingCartTexture = getTextureForIcon( atlas, "add-shopping-cart-icon" );
            alarmAddTexture = getTextureForIcon( atlas, "alarm-add-icon" );
            alarmTexture = getTextureForIcon( atlas, "alarm-icon" );
            alarmOffTexture = getTextureForIcon( atlas, "alarm-off-icon" );
            alarmOnTexture = getTextureForIcon( atlas, "alarm-on-icon" );
            androidTexture = getTextureForIcon( atlas, "android-icon" );
            announcementTexture = getTextureForIcon( atlas, "announcement-icon" );
            appsTexture = getTextureForIcon( atlas, "apps-icon" );
            archiveTexture = getTextureForIcon( atlas, "archive-icon" );
            arrowBackTexture = getTextureForIcon( atlas, "arrow-back-icon" );
            arrowDropDownCircleTexture = getTextureForIcon( atlas, "arrow-drop-down-circle-icon" );
            arrowDropDownTexture = getTextureForIcon( atlas, "arrow-drop-down-icon" );
            arrowDropUpTexture = getTextureForIcon( atlas, "arrow-drop-up-icon" );
            arrowForwardTexture = getTextureForIcon( atlas, "arrow-forward-icon" );
            aspectRatioTexture = getTextureForIcon( atlas, "aspect-ratio-icon" );
            assessmentTexture = getTextureForIcon( atlas, "assessment-icon" );
            assignmentTexture = getTextureForIcon( atlas, "assignment-icon" );
            assignmentIndTexture = getTextureForIcon( atlas, "assignment-ind-icon" );
            assignmentLateTexture = getTextureForIcon( atlas, "assignment-late-icon" );
            assignmentReturnTexture = getTextureForIcon( atlas, "assignment-return-icon" );
            assignmentReturnedTexture = getTextureForIcon( atlas, "assignment-returned-icon" );
            assignmentTurnedInTexture = getTextureForIcon( atlas, "assignment-turned-in-icon" );
            autoRenewTexture = getTextureForIcon( atlas, "auto-renew-icon" );
            backspaceTexture = getTextureForIcon( atlas, "backspace-icon" );
            backupTexture = getTextureForIcon( atlas, "backup-icon" );
            blockTexture = getTextureForIcon( atlas, "block-icon" );
            bookTexture = getTextureForIcon( atlas, "book-icon" );
            bookmarkTexture = getTextureForIcon( atlas, "bookmark-icon" );
            bookmarkOutlineTexture = getTextureForIcon( atlas, "bookmark-outline-icon" );
            bugReportTexture = getTextureForIcon( atlas, "bug-report-icon" );
            cachedTexture = getTextureForIcon( atlas, "cached-icon" );
            cakeTexture = getTextureForIcon( atlas, "cake-icon" );
            cancelTexture = getTextureForIcon( atlas, "cancel-icon" );
            checkCircleTexture = getTextureForIcon( atlas, "check-circle-icon" );
            checkTexture = getTextureForIcon( atlas, "check-icon" );
            chevronLeftTexture = getTextureForIcon( atlas, "chevron-left-icon" );
            chevronRightTexture = getTextureForIcon( atlas, "chevron-right-icon" );
            classTexture = getTextureForIcon( atlas, "class-icon" );
            clearTexture = getTextureForIcon( atlas, "clear-icon" );
            closeTexture = getTextureForIcon( atlas, "close-icon" );
            contentCopyTexture = getTextureForIcon( atlas, "content-copy-icon" );
            contentCutTexture = getTextureForIcon( atlas, "content-cut-icon" );
            contentPasteTexture = getTextureForIcon( atlas, "content-paste-icon" );
            createTexture = getTextureForIcon( atlas, "create-icon" );
            creditCardTexture = getTextureForIcon( atlas, "credit-card-icon" );
            dashboardTexture = getTextureForIcon( atlas, "dashboard-icon" );
            deleteTexture = getTextureForIcon( atlas, "delete-icon" );
            descriptionTexture = getTextureForIcon( atlas, "description-icon" );
            dnsTexture = getTextureForIcon( atlas, "dns-icon" );
            domainTexture = getTextureForIcon( atlas, "domain-icon" );
            doneAllTexture = getTextureForIcon( atlas, "done-all-icon" );
            doneTexture = getTextureForIcon( atlas, "done-icon" );
            draftsTexture = getTextureForIcon( atlas, "drafts-icon" );
            errorTexture = getTextureForIcon( atlas, "error-icon" );
            eventTexture = getTextureForIcon( atlas, "event-icon" );
            exitToAppTexture = getTextureForIcon( atlas, "exit-to-app-icon" );
            expandLessTexture = getTextureForIcon( atlas, "expand-less-icon" );
            expandMoreTexture = getTextureForIcon( atlas, "expand-more-icon" );
            exploreTexture = getTextureForIcon( atlas, "explore-icon" );
            extensionTexture = getTextureForIcon( atlas, "extension-icon" );
            faceTexture = getTextureForIcon( atlas, "face-icon" );
            favoriteTexture = getTextureForIcon( atlas, "favorite-icon" );
            favoriteOutlineTexture = getTextureForIcon( atlas, "favorite-outline-icon" );
            filterListTexture = getTextureForIcon( atlas, "filter-list-icon" );
            findInPageTexture = getTextureForIcon( atlas, "find-in-page-icon" );
            findReplaceTexture = getTextureForIcon( atlas, "find-replace-icon" );
            flagTexture = getTextureForIcon( atlas, "flag-icon" );
            flipToBackTexture = getTextureForIcon( atlas, "flip-to-back-icon" );
            flipToFrontTexture = getTextureForIcon( atlas, "flip-to-front-icon" );
            forwardTexture = getTextureForIcon( atlas, "forward-icon" );
            fullscreenExitTexture = getTextureForIcon( atlas, "fullscreen-exit-icon" );
            fullscreenTexture = getTextureForIcon( atlas, "fullscreen-icon" );
            gestureTexture = getTextureForIcon( atlas, "gesture-icon" );
            getAppTexture = getTextureForIcon( atlas, "get-app-icon" );
            gradeTexture = getTextureForIcon( atlas, "grade-icon" );
            groupAddTexture = getTextureForIcon( atlas, "group-add-icon" );
            groupTexture = getTextureForIcon( atlas, "group-icon" );
            groupWorkTexture = getTextureForIcon( atlas, "group-work-icon" );
            helpTexture = getTextureForIcon( atlas, "help-icon" );
            highlightRemoveTexture = getTextureForIcon( atlas, "highlight-remove-icon" );
            historyTexture = getTextureForIcon( atlas, "history-icon" );
            homeTexture = getTextureForIcon( atlas, "home-icon" );
            httpsTexture = getTextureForIcon( atlas, "https-icon" );
            inboxTexture = getTextureForIcon( atlas, "inbox-icon" );
            infoTexture = getTextureForIcon( atlas, "info-icon" );
            infoOutlineTexture = getTextureForIcon( atlas, "info-outline-icon" );
            inputTexture = getTextureForIcon( atlas, "input-icon" );
            invertColorsTexture = getTextureForIcon( atlas, "invert-colors-icon" );
            labelTexture = getTextureForIcon( atlas, "label-icon" );
            labelOutlineTexture = getTextureForIcon( atlas, "label-outline-icon" );
            languageTexture = getTextureForIcon( atlas, "language-icon" );
            launchTexture = getTextureForIcon( atlas, "launch-icon" );
            linkTexture = getTextureForIcon( atlas, "link-icon" );
            listTexture = getTextureForIcon( atlas, "list-icon" );
            locationCityTexture = getTextureForIcon( atlas, "location-city-icon" );
            lockTexture = getTextureForIcon( atlas, "lock-icon" );
            lockOpenTexture = getTextureForIcon( atlas, "lock-open-icon" );
            lockOutlineTexture = getTextureForIcon( atlas, "lock-outline-icon" );
            loyaltyTexture = getTextureForIcon( atlas, "loyalty-icon" );
            mailTexture = getTextureForIcon( atlas, "mail-icon" );
            markUnreadMailboxTexture = getTextureForIcon( atlas, "mark-unread-mailbox-icon" );
            markUnreadTexture = getTextureForIcon( atlas, "mark-unread-icon" );
            menuTexture = getTextureForIcon( atlas, "menu-icon" );
            moodTexture = getTextureForIcon( atlas, "mood-icon" );
            moreHorizontalTexture = getTextureForIcon( atlas, "more-horizontal-icon" );
            moreVerticalTexture = getTextureForIcon( atlas, "more-vertical-icon" );
            noteAddTexture = getTextureForIcon( atlas, "note-add-icon" );
            notificationsTexture = getTextureForIcon( atlas, "notifications-icon" );
            notificationsNoneTexture = getTextureForIcon( atlas, "notifications-none-icon" );
            notificationsOffTexture = getTextureForIcon( atlas, "notifications-off-icon" );
            notificationsOnTexture = getTextureForIcon( atlas, "notifications-on-icon" );
            notificationsPausedTexture = getTextureForIcon( atlas, "notifications-paused-icon" );
            openInBrowserTexture = getTextureForIcon( atlas, "open-in-browser-icon" );
            openInNewTexture = getTextureForIcon( atlas, "open-in-new-icon" );
            openWithTexture = getTextureForIcon( atlas, "open-with-icon" );
            pageViewTexture = getTextureForIcon( atlas, "page-view-icon" );
            pagesTexture = getTextureForIcon( atlas, "pages-icon" );
            partyModeTexture = getTextureForIcon( atlas, "party-mode-icon" );
            paymentTexture = getTextureForIcon( atlas, "payment-icon" );
            peopleTexture = getTextureForIcon( atlas, "people-icon" );
            peopleOutlineTexture = getTextureForIcon( atlas, "people-outline-icon" );
            permCameraMicTexture = getTextureForIcon( atlas, "perm-camera-mic-icon" );
            permContactCalTexture = getTextureForIcon( atlas, "perm-contact-cal-icon" );
            permDataSettingTexture = getTextureForIcon( atlas, "perm-data-setting-icon" );
            permDeviceInfoTexture = getTextureForIcon( atlas, "perm-device-info-icon" );
            permIdentityTexture = getTextureForIcon( atlas, "perm-identity-icon" );
            permMediaTexture = getTextureForIcon( atlas, "perm-media-icon" );
            permPhoneMsgTexture = getTextureForIcon( atlas, "perm-phone-msg-icon" );
            permScanWifiTexture = getTextureForIcon( atlas, "perm-scan-wifi-icon" );
            personAddTexture = getTextureForIcon( atlas, "person-add-icon" );
            personTexture = getTextureForIcon( atlas, "person-icon" );
            personOutlineTexture = getTextureForIcon( atlas, "person-outline-icon" );
            pictureInPictureTexture = getTextureForIcon( atlas, "picture-in-picture-icon" );
            plusOneTexture = getTextureForIcon( atlas, "plus-one-icon" );
            pollTexture = getTextureForIcon( atlas, "poll-icon" );
            polymerTexture = getTextureForIcon( atlas, "polymer-icon" );
            printTexture = getTextureForIcon( atlas, "print-icon" );
            publicTexture = getTextureForIcon( atlas, "public-icon" );
            queryBuilderTexture = getTextureForIcon( atlas, "query-builder-icon" );
            questionAnswerTexture = getTextureForIcon( atlas, "question-answer-icon" );
            receiptTexture = getTextureForIcon( atlas, "receipt-icon" );
            redeemTexture = getTextureForIcon( atlas, "redeem-icon" );
            redoTexture = getTextureForIcon( atlas, "redo-icon" );
            refreshTexture = getTextureForIcon( atlas, "refresh-icon" );
            removeCircleTexture = getTextureForIcon( atlas, "remove-circle-icon" );
            removeCircleOutlineTexture = getTextureForIcon( atlas, "remove-circle-outline-icon" );
            removeTexture = getTextureForIcon( atlas, "remove-icon" );
            reorderTexture = getTextureForIcon( atlas, "reorder-icon" );
            replyAllTexture = getTextureForIcon( atlas, "reply-all-icon" );
            replyTexture = getTextureForIcon( atlas, "reply-icon" );
            reportTexture = getTextureForIcon( atlas, "report-icon" );
            reportProblemTexture = getTextureForIcon( atlas, "report-problem-icon" );
            restoreTexture = getTextureForIcon( atlas, "restore-icon" );
            roomTexture = getTextureForIcon( atlas, "room-icon" );
            saveTexture = getTextureForIcon( atlas, "save-icon" );
            scheduleTexture = getTextureForIcon( atlas, "schedule-icon" );
            schoolTexture = getTextureForIcon( atlas, "school-icon" );
            searchTexture = getTextureForIcon( atlas, "search-icon" );
            selectAllTexture = getTextureForIcon( atlas, "select-all-icon" );
            sendTexture = getTextureForIcon( atlas, "send-icon" );
            settingsApplicationsTexture = getTextureForIcon( atlas, "settings-applications-icon" );
            settingsBackupRestoreTexture = getTextureForIcon( atlas, "settings-backup-restore-icon" );
            settingsBluetoothTexture = getTextureForIcon( atlas, "settings-bluetooth-icon" );
            settingsCellTexture = getTextureForIcon( atlas, "settings-cell-icon" );
            settingsDisplayTexture = getTextureForIcon( atlas, "settings-display-icon" );
            settingsEthernetTexture = getTextureForIcon( atlas, "settings-ethernet-icon" );
            settingsTexture = getTextureForIcon( atlas, "settings-icon" );
            settingsInputAntennaTexture = getTextureForIcon( atlas, "settings-input-antenna-icon" );
            settingsInputComponentTexture = getTextureForIcon( atlas, "settings-input-component-icon" );
            settingsInputCompositeTexture = getTextureForIcon( atlas, "settings-input-composite-icon" );
            settingsInputHDMITexture = getTextureForIcon( atlas, "settings-input-hdmi-icon" );
            settingsInputSVideoTexture = getTextureForIcon( atlas, "settings-input-svideo-icon" );
            settingsOverscanTexture = getTextureForIcon( atlas, "settings-overscan-icon" );
            settingsPhoneTexture = getTextureForIcon( atlas, "settings-phone-icon" );
            settingsPowerTexture = getTextureForIcon( atlas, "settings-power-icon" );
            settingsRemoteTexture = getTextureForIcon( atlas, "settings-remote-icon" );
            settingsVoiceTexture = getTextureForIcon( atlas, "settings-voice-icon" );
            shareTexture = getTextureForIcon( atlas, "share-icon" );
            shopTexture = getTextureForIcon( atlas, "shop-icon" );
            shopTwoTexture = getTextureForIcon( atlas, "shop-two-icon" );
            shoppingBasketTexture = getTextureForIcon( atlas, "shopping-basket-icon" );
            shoppingCartTexture = getTextureForIcon( atlas, "shopping-cart-icon" );
            sortTexture = getTextureForIcon( atlas, "sort-icon" );
            speakerNotesTexture = getTextureForIcon( atlas, "speaker-notes-icon" );
            spellCheckTexture = getTextureForIcon( atlas, "spell-check-icon" );
            starRateTexture = getTextureForIcon( atlas, "star-rate-icon" );
            starsTexture = getTextureForIcon( atlas, "stars-icon" );
            storeTexture = getTextureForIcon( atlas, "store-icon" );
            subjectTexture = getTextureForIcon( atlas, "subject-icon" );
            supervisorAccountTexture = getTextureForIcon( atlas, "supervisor-account-icon" );
            swapHorizontalTexture = getTextureForIcon( atlas, "swap-horizontal-icon" );
            swapVerticalCircleTexture = getTextureForIcon( atlas, "swap-vertical-circle-icon" );
            swapVerticalTexture = getTextureForIcon( atlas, "swap-vertical-icon" );
            systemUpdateTvTexture = getTextureForIcon( atlas, "system-update-tv-icon" );
            tabTexture = getTextureForIcon( atlas, "tab-icon" );
            tabUnselectedTexture = getTextureForIcon( atlas, "tab-unselected-icon" );
            textFormatTexture = getTextureForIcon( atlas, "text-format-icon" );
            theatersTexture = getTextureForIcon( atlas, "theaters-icon" );
            thumbDownTexture = getTextureForIcon( atlas, "thumb-down-icon" );
            thumbUpTexture = getTextureForIcon( atlas, "thumb-up-icon" );
            thumbsUpDownTexture = getTextureForIcon( atlas, "thumbs-up-down-icon" );
            tocTexture = getTextureForIcon( atlas, "toc-icon" );
            todayTexture = getTextureForIcon( atlas, "today-icon" );
            trackChangesTexture = getTextureForIcon( atlas, "track-changes-icon" );
            translateTexture = getTextureForIcon( atlas, "translate-icon" );
            trendingDownTexture = getTextureForIcon( atlas, "trending-down-icon" );
            trendingNeutralTexture = getTextureForIcon( atlas, "trending-neutral-icon" );
            trendingUpTexture = getTextureForIcon( atlas, "trending-up-icon" );
            turnedInTexture = getTextureForIcon( atlas, "turned-in-icon" );
            turnedInNotTexture = getTextureForIcon( atlas, "turned-in-not-icon" );
            undoTexture = getTextureForIcon( atlas, "undo-icon" );
            unfoldLessTexture = getTextureForIcon( atlas, "unfold-less-icon" );
            unfoldMoreTexture = getTextureForIcon( atlas, "unfold-more-icon" );
            verifiedUserTexture = getTextureForIcon( atlas, "verified-user-icon" );
            videocamTexture = getTextureForIcon( atlas, "videocam-icon" );
            viewAgendaTexture = getTextureForIcon( atlas, "view-agenda-icon" );
            viewArrayTexture = getTextureForIcon( atlas, "view-array-icon" );
            viewCarouselTexture = getTextureForIcon( atlas, "view-carousel-icon" );
            viewColumnTexture = getTextureForIcon( atlas, "view-column-icon" );
            viewDayTexture = getTextureForIcon( atlas, "view-day-icon" );
            viewHeadlineTexture = getTextureForIcon( atlas, "view-headline-icon" );
            viewListTexture = getTextureForIcon( atlas, "view-list-icon" );
            viewModuleTexture = getTextureForIcon( atlas, "view-module-icon" );
            viewQuiltTexture = getTextureForIcon( atlas, "view-quilt-icon" );
            viewStreamTexture = getTextureForIcon( atlas, "view-stream-icon" );
            viewWeekTexture = getTextureForIcon( atlas, "view-week-icon" );
            visibilityTexture = getTextureForIcon( atlas, "visibility-icon" );
            visibilityOffTexture = getTextureForIcon( atlas, "visibility-off-icon" );
            walletGiftCardTexture = getTextureForIcon( atlas, "wallet-gift-card-icon" );
            walletMembershipTexture = getTextureForIcon( atlas, "wallet-membership-icon" );
            walletTravelTexture = getTextureForIcon( atlas, "wallet-travel-icon" );
            warningTexture = getTextureForIcon( atlas, "warning-icon" );
            whatsHotTexture = getTextureForIcon( atlas, "whats-hot-icon" );
            workTexture = getTextureForIcon( atlas, "work-icon" );
        }

        private static function getTextureForIcon( atlas:TextureAtlas, name:String ):Texture {
            const texture:Texture = atlas.getTexture( name );
            if( !texture ) {
                trace("[UniflatThemeIcons - Warning] Texture for icon '" + name + "' not found.");
            }
            return texture;
        }

    }

}
